### ISSUE TITLE
Great article, but react-router 2.0.0 had effects

### ISSUE THREAD

**Issue by richb-hanover** [jackfranklin/universal-react-example#3]
I really enjoyed this article on using react-router. It is a simple, clear example of how server side rendering works.

But... react-router 2.0.0 hit in February 2016, and changed an interface. The current code works, but gives error messages of 

```
Warning: [react-router] `RoutingContext` has been renamed to `RouterContext`. Please use `import { RouterContext } from 'react-router'`. http://tiny.cc/router-routercontext
```

The solution is to change RoutingContext to RouterContext in two places in server.js

Thanks for this tutorial!

**Comment by jackfranklin** [comment]
@richb-hanover thanks! If you fancy doing a PR with the above change that'd be awesome, else I'll try to do it at some point :)

**Comment by richb-hanover** [comment]
What a great learning opportunity... I cloned your repo, ran `npm start` and... No error messages!

After some farbling around, I see that your repo specifies `"react-router": "^1.0.0"`, but using `npm install --save` today installs 2.0.1. That generates the error message (see https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#other-changes for details).

So... Multiple fixes are needed:
1. You should update your blog to s/RoutingContext/RouterContext/g This will make your article work without the warnings for anyone new who comes along to read it.
2. I'm not all the way through your article. I know there are changes to history in the newer react-router. That may require further changes to your blog - I'll let you know in this thread.
3. Your repo works fine as-is. But it now showcases react-router@1.0.0, which is no longer current. Once I work my way through the rest of the article, I will take a whack at making the pull request as requested.

Thanks again.
