### ISSUE TITLE
Minimum universal react API

### ISSUE THREAD

**Issue by guidsen** [jackfranklin/universal-react-example#7]
Hi, I've been working on https://github.com/guidsen/react-simple-universal that solved the boilerplate involved with universal React Apps.

I'm really curious about your thoughts about this and would love to have some help evolving this repo.

**Comment by jackfranklin** [comment]
This is really cool, I've been planning to build something like that myself but you beat me too it!

I would like this repo to stay as is so it's a simple example that people can build from, but I'd love to contrib to your work and help in anyway I can. I'm going to close this but please tag me on any issues in your repo that you'd like my thoughts on :+1:
