### ISSUE TITLE
Server routing doesnt match client routing

### ISSUE THREAD

**Issue by abeikverdi** [jackfranklin/universal-react-example#9]
if I GET /about it returns me the index page and it only goes to about if I use #/about which does it in the client side. I also have this warning on my console:

`build.js:1108 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) eactid="4"><a href="#/" data-reactid="5"
 (server) eactid="4"><a href="/" data-reactid="5">`

How can I fix this? I want the server to return the whole about in GET /about request. Seems like only client side is working for me. Am I missing something?

**Comment by abeikverdi** [comment]
I cloned you repository and it worked correctly. I modified the code while was following your tutorial. Like I used normal a tags instead of React Router Link. Whats the thing that syncs client and servers routing? You let express gets any routes and then create routes using React Router.

**Comment by jackfranklin** [comment]
I think the problem here looks to be that the client needs to use the html5 history API mode in React Router. I thought it did, but maybe not.

**Comment by abeikverdi** [comment]
Right. Your code works as I said earlier. For some reason mine wasn't working when I followed the tutorial but after cloning your repository everything works just fine.
